name: udemy_flutter_sns
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.8.1
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.0.2
  firebase_core: ^2.9.0
  firebase_auth: ^4.4.1
  cloud_firestore: ^4.5.1
  firebase_analytics: ^10.2.0
  google_fonts: ^4.0.3
  pull_to_refresh: ^2.0.0
  image_cropper: ^1.4.1
  shared_preferences: ^2.0.13
  url_launcher: ^6.0.20
  clipboard: ^0.1.3
  flutter_launcher_icons: ^0.12.0
  flash: ^3.1.0
  uuid: ^3.0.5
  image_picker: ^0.8.4+11
  flutter_svg: ^1.1.6
  firebase_storage: ^11.1.0
  firebase_crashlytics: ^3.1.0
  fluttertoast: ^8.0.9
  http: ^0.13.6
  flutter_dotenv: ^5.1.0
  algolia: ^1.1.1
  freezed_annotation: ^2.1.0

  flutter_localizations:
    sdk: flutter
  material_floating_search_bar_2: ^0.5.0

dev_dependencies:
  build_runner: ^2.2.0
  freezed: ^2.1.0+1
  json_serializable: ^6.3.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

dependency_overrides:
  intl: ^0.18.0-nullsafety.2

flutter:
  uses-material-design: true

  assets:
    - .env

